apiVersion: apps/v1beta2
apiVersion: v1
kind: Service
metadata:
  name: webuiapi
spec:
  selector:
    app: webui
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: webui
  labels:
    app: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: team8containers.azurecr.io/webui:BUILD_ID
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: containersecret        
---
